version: '3.1'
services:
  go-emby2openlist:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-emby2openlist
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
      - ./ssl:/app/ssl
      - ./logs:/app/logs
    ports:
      - 8095:8095 # http
      - 8094:8094 # https
      - 8097:8097 # auth server